server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


spring:
  cloud:
    gateway:
      routes:
        - id: teamsModule
          uri: lb://teams
          predicates:
            - Path=/teams/**
        - id: integrationModule
          uri: lb://integration
          predicates:
            - Path=/integration/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: google
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri-template: ${REDIRECT_OAUTH_URI:http://localhost:8080/login/oauth2/code/250364537108-r38p26rsmcu4vtpbkb5j7dsb3tu6cs08.apps.googleusercontent.com}
            scope: email,profile,openid
        provider:
          google:
            authorization-uri: //accounts.google.com/o/oauth2/v2/auth
            token-uri: //www.googleapis.com/oauth2/v4/token
            user-info-uri: //www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: profile
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs